controllers/EquiposController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Equipos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EquiposController implements the CRUD actions for Equipos model.
 */
class EquiposController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Equipos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Equipos::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Equipos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Equipos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Equipos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Equipos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Equipos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Equipos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Equipos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Equipos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Jugadores;
use app\models\Equipos;
use yii\data\ActiveDataProvider;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionListajugadores(){
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()->select([ 'rol', 'equipos.nombre as Equipo', 'jugadores.nombre'])
                ->innerJoinWith('codEquipo', false),
            'pagination'=>[
                'pageSize'=>30
            ]
        ]);
        
        return $this -> render("ListaJugadores",[
            "resultados"=>$dataProvider,
            "campos"=>['nombre', 'rol', 'Equipo']
        ]);
    }
    public function actionListaequipos(){
        $dataProvider = new ActiveDataProvider([
            'query' => Equipos::find()->select('nombre, localización, nom_director'),
            'pagination'=>[
                'pageSize'=>30
            ]
        ]);
        
        return $this -> render("ListaEquipos",[
            "resultados"=>$dataProvider,
            "campos"=>['nombre', 'localización', 'nom_director']
        ]);
    }
    public function actionCreatabla()
    {
        return $this->render('creatabla');
    }
    public function actionNoticias()
    {
        return $this->render('noticias');
    }
     public function actionUltimospartidos(){
        $dataProvider = new ActiveDataProvider([
            'query' => Jugadores::find()->select([ 'rol', 'nombre']),
            'pagination'=>[
                'pageSize'=>5
            ]
        ]);
        
        return $this -> render("index",[
            "resultados"=>$dataProvider,
            "campos"=>['nombre', 'rol']
        ]);
    }
}

views/site/ListaEquipos.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
?>
    <?= GridView::widget([
       'dataProvider' => $resultados,
        'columns' => $campos
    ]); ?> 
     <?= Html::a('Inscribir Equipo', ['equipos/create'], ['class'=>'btn btn-primary'])?>

views/site/ListaJugadores.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
?>
    <?= GridView::widget([
        'dataProvider' => $resultados,
        'columns' => $campos
    ]); ?>
    <?= Html::a('Inscribir Jugador', ['jugadores/create'], ['class'=>'btn btn-primary'])?>
    <?= Html::a('Editar Lista', ['jugadores/index'], ['class'=>'btn btn-secondary'])?>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
    <!--About Us-Hero Section-->
    <section class="service-area green-service">
        <div class="container">
            <div class="row">
                <h1>Nosotros</h1>
            </div>
        </div>
    </section>
    <!--/About Us-Hero Section-->

    <!--About-team Section-->
    <section class="About-team">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="team-image">
                        <img class="posicionado-arriba" src="../../../assets/images/prueba.jpg"  alt="">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="colo-content ab-us">
                        <p>Equipo Especializado</p>
                        <h2>Pasión Por Nuestro Trabajo</h2>
                        <p>For people like me, book are something solid and
                            real, whereas digital stuff is a bit more ethereal.
                            I like the trophy on my shelf, the presence in my
                            home. A nice book is just as valuable.
                        </p>

                        <p>Let's face it, a hell of a lot more useful. For people
                            like me, book are something solid and real where
                            digital stuff is a bit more ethereal. For people.</p>

                        <div class="btn-learn bc-3">
                            <span class="learn-ab"><a href="service.html">Nuestros Servicios</a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/About-team Section-->

    <!--Our-experience Section-->
    <section class="our-experience">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="o-e-content">
                        <p>Porque Elegirnos</p>
                        <h1>Experiencia En Todo Tipo De Pintura</h1>
                        <p>For people like me, book are something solid and real, whereas digital stuff
                            is a bit more ethereal. I like the trophy on my shelf, the presence in my
                            home. A nice book is just as valuable. Let's face it, a hell of a lot more useful.
                        </p>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="expart">
                                <div class="expart-icon ei-green">
                                    <span class="flaticon-paint ex-1"></span>
                                </div>
                                <div class="expart-content">
                                    <h4>Color Expert</h4>
                                    <p>For people like book something
                                        real, whereas digital stuff is
                                        bit more ethereal like the troph.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="expart">
                                <div class="expart-icon ei-green">
                                    <span class="flaticon-paint-1 ex-1"></span>
                                </div>
                                <div class="expart-content">
                                    <h4>Color Expert</h4>
                                    <p>For people like book something
                                        real, whereas digital stuff is
                                        bit more ethereal like the troph.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="expart">
                                <div class="expart-icon ei-green">
                                    <span class="flaticon-graphic-tool ex-1"></span>
                                </div>
                                <div class="expart-content">
                                    <h4>Color Expert</h4>
                                    <p>For people like book something
                                        real, whereas digital stuff is
                                        bit more ethereal like the troph.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="expart">
                                <div class="expart-icon ei-green">
                                    <span class="flaticon-pantone ex-1"></span>
                                </div>
                                <div class="expart-content">
                                    <h4>Color Expert</h4>
                                    <p>For people like book something
                                        real, whereas digital stuff is
                                        bit more ethereal like the troph.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!--/Our-experience Section-->

    <!-- care-about Section-->
    <section class="care-about">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img class="posicionado" src="../../../assets/images/prueba.jpg" alt="">
                </div>
                <div class="col-md-6">
                    <div class="c-a-content">
                        <p>Te Cuidamos</p>
                        <h2>Nosotros Te Ayudamos</h2>
                        <p>For people like me, book are something solid and real, whereas digital
                            stuff is a bit more ethereal. I like the trophy on my shelf, the presence
                            in my home. A nice book is just as valuable. Let's face it, a hell of a lot
                            more useful. For people like me, book are something solid and real
                            where digital stuff is a bit more. Digital stuff is a bit more ethereal.
                            ike the trophy on my shelf,</p>
                        <p>The presence in my home. A nice book is just as valuable. Let's face it,
                            a hell of a lot more useful. For people like me, book are something
                            solid and real where digital stuff.</p>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="cap-1 acp-green">
                                <div class="cap-text">
                                    <span class="cap-m"><span class="counterUp">140</span> K+</span>
                                    <p>Proyectos Finalizados</p>
                                </div>
                            </div>
                            <div class="cap-1 cap-2 acp-green">
                                <div class="cap-text">
                                    <span class="cap-m"><span class="counterUp">212</span> &nbsp;K+</span>
                                    <p>Usuarios Regulares</p>
                                </div>
                            </div>
                            <div class="cap-1 cap-3 acp-green">
                                <div class="cap-text ">
                                    <span class="cap-m"><span class="counterUp">121</span>&nbsp; +</span>
                                    <p>Premios</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /care-about Section-->

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contacto';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Gracias por ponerte en contacto con LaCopa. Tu mensaje sera atendido con la mayor brevedad posible.
        </div>

        <p>
            Tome nota que ningun email es enviado mientras la aplicación esta en desarrollo, el mensaje es tranferido y guardado en uno de nuestros archivos.
        </p>

    <?php else: ?>
        <br>
        <h4 class="text-center txt-yllw">
            Para contactar con la compañia para inscribirte a un torneo o para recibir información, por favor, rellene el siguiente formulario.
        </h4>
        <br>
        <br>
        <br>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'nombre')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'asunto') ?>

                    <?= $form->field($model, 'mensaje')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Enviar', ['class' => 'btn btn-default', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/creatabla.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Crear Tabla';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-3 text-center well well-red">
        <h4>Tabla de 4 equipos<br></br></h4>
        <p class="text-center">
            <?= Html::a('Acceder', ['site/tabla4'], ['class'=>'btn btn-primary btn-block'])?>
        </p>
    </div>
    <div class="col-md-3 text-center well well-red">
        <h4>Tabla de 8 equipos<br></br></h4>

        <p>
            <?= Html::a('Acceder', ['site/tabla8'], ['class'=>'btn btn-primary btn-block'])?>
        </p>
    </div>
    <div class="col-md-3 text-center well well-red">
        <h4>Tabla de 16 equipos<br></br></h4>

        <p>
            <?= Html::a('Acceder', ['site/tabla16'], ['class'=>'btn btn-primary btn-block'])?>
        </p>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\grid\GridView;
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Torneos LaCopa</h1>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-md-3 text-center well well-red">
                <h4>Listado de jugadores<br></br></h4>
                <p class="text-center">
                    <?= Html::a('Acceder', ['site/listajugadores'], ['class'=>'btn btn-primary btn-block'])?>
                </p>
            </div>
            <div class="col-md-3 text-center well well-red">
                <h4>Listado de equipos<br></br></h4>

                <p>
                    <?= Html::a('Acceder', ['site/listaequipos'], ['class'=>'btn btn-primary btn-block'])?>
                </p>
            </div>
            <div class="col-md-3 text-center well well-red">
                <h4>Creación de tablas de torneo<br></br></h4>

                <p>
                    <?= Html::a('Acceder', ['site/creatabla'], ['class'=>'btn btn-primary btn-block'])?>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 text-center well well-red">
                <h4>Texto de Ejemplo<br></br></h4>
                <p class="text-center">
                    <?= Html::a('Acceder', ['#'], ['class'=>'btn btn-primary btn-block'])?>
                </p>
            </div>
            <div class="col-md-3 text-center well well-red">
                <h4>Texto de Ejemplo<br></br></h4>

                <p>
                    <?= Html::a('Acceder', ['#'], ['class'=>'btn btn-primary btn-block'])?>
                </p>
            </div>
            <div class="col-md-3 text-center well well-red">
                <h4>Texto de Ejemplo<br></br></h4>

                <p>
                    <?= Html::a('Acceder', ['#'], ['class'=>'btn btn-primary btn-block'])?>
                </p>
            </div>
        </div>
        <div class="separador">
            <div class="col-md-6">
                <img class="posicionado-inicio" src="/LaCopa/assets/images/prueba.jpg"  alt="">
            </div>
            <div class="col-md-6">
                <p class="text-justify txt-blk centrado align-items-center">
                    For people like me, book are something solid and real, whereas digital stuff is a bit more ethereal. I like the trophy on my shelf, the presence in my home. A nice book is just as valuable. Let's face it, a hell of a lot more useful. For people like me, book are something solid and real where digital stuff is a bit more. Digital stuff is a bit more ethereal. ike the trophy on my shelf,

The presence in my home. A nice book is just as valuable. Let's face it, a hell of a lot more useful. For people like me, book are something solid and real where digital stuff.
                    For people like me, book are something solid and real, whereas digital stuff is a bit more ethereal. I like the trophy on my shelf, the presence in my home. A nice book is just as valuable. Let's face it, a hell of a lot more useful. For people like me, book are something solid and real where digital stuff is a bit more. Digital stuff is a bit more ethereal. ike the trophy on my shelf,

The presence in my home. A nice book is just as valuable. Let's face it, a hell of a lot more useful. For people like me, book are something solid and real where digital stuff.
                </p>
            </div>
        </div>
        <div class="jumbotron contenido">
            <h1>Noticias</h1>
        </div>
        <div class="col-lg-12">
            <div class="row news">
              <div class="col-md-4">
                <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
                  <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
                  <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
                  <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
                </div>
              </div>
            </div>
        </div>
        <div class="jumbotron contenido2">
            <h1>Ultimos Partidos</h1>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/noticias.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="main-news">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="row news">
          <div class="col-md-4">
            <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
              <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
              <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
              <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
              <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
              <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg"  alt="website template image">
              <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
              <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
              <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
            </div>
          </div>
          <div class="col-md-4">
              <div class="mn-img"><img class="darkening" src="/LaCopa/assets/images/prueba.jpg" alt="website template image">
              <div class="mn-title"><a href="https://www.free-css.com/free-css-templates">Lorem ipsum dolor sit</a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>